outerbase/studio

drizzle/0001_crazy_eternals.sql
drizzle/meta/0001_snapshot.json
drizzle/meta/_journal.json
src/app/login/github/callback/route.ts
src/app/login/github/route.ts
src/db/schema.ts

feat: save gh email when login

---

package-lock.json
src/app/login/github/callback/route.ts
src/app/login/google/callback/route.ts
src/app/login/google/route.ts
src/app/login/page.tsx
src/controllers/auth.ts
src/env.ts
src/lib/auth.ts

I introduced 3 new environment variables
`BASE_URL=http://localhost:3000` it's for google auth client redirect
`GOOGLE_CLIENT_ID=`
`GOOGLE_CLIENT_SECRET=`
I have also added AuthContoller [33-google-login/src/controllers/auth.ts](https://github.com/invisal/libsql-studio/blob/33-google-login/src/controllers/auth.ts) for easier to integrate with new provider.
To add login in with google, first need to create a new project at https://console.cloud.google.com/
Then create a consent screen at https://console.cloud.google.com/apis/credentials/consent with the scope below
Then need to create 2 credentials OAuth client ID one for development and another one for production
for development need to config like below

feat[auth]: add login with google

---

package-lock.json
package.json
src/app/layout.tsx
src/components/block-editor/extensions/file-upload.ts
src/components/query-result-table.tsx
src/components/ui/sonner.tsx
src/lib/file-upload.ts
src/lib/utils.ts
src/lib/with-user.ts

- Added an `Upload File` button to the cell context menu. Allowing user to upload file to R2 and set the file url into the current focused cell.
- Added `Toaster` component from sonner
Tested on:
- Arc browser running on chromium
- Safari
https://github.com/invisal/libsql-studio/assets/106462074/5c912ae7-2366-4062-9461-d58dc0c8f70d
https://github.com/invisal/libsql-studio/assets/106462074/383c10f6-11c6-4cc8-8ee6-65f5dad4e437

feat: add upload file to cell

---

package-lock.json
package.json
src/app/api/upload/route.ts
src/lib/r2.ts

Add better file type detection for `/api/upload`. This is done using the `magic-bytes` package which has support for browser environment and a tons of file type support. 
- try to detect file type information using `magic-bytes`
- fallback to the `File` object `file.type` and `file.name`
We need to use a package that support browser api as we are running on edge.
---
Currently we store the filename in our `user_files` table. But in the case that let's say user upload a file of type `jpeg`.
But the file name is instead `filename.pdf`. In this case we correct the file type but we still store the filename as `filename.pdf`, do you have any suggestion for this?
---
In the demo, I renamed a jpeg screenshot into `.pdf` but the api detected it as jpeg, and use that instead. …

feat: better file type detection

---

gui/src/components/context-menu-handler.tsx

This PR change the `cancelable: false` to `cancelable: true` in the context menu `MouseEvent`. 
This allow the event to be prevented, e.g. `e.preventDefault()`
https://developer.mozilla.org/en-US/docs/Web/API/Event/cancelable
https://github.com/invisal/libsql-studio/assets/106462074/1806718d-6559-4962-ba57-e77d2cbcdc06
closes #85

fix(gui): stop safari from opening the native menu

---

src/components/gui/query-result-table.tsx

I wanted to copy a row as javascript object, but the button wasn't there
https://github.com/user-attachments/assets/625aafaf-ff24-4ac6-8392-9782baca745b

feat: add export rows as json

---

src/components/gui/query-result-table.tsx
src/components/gui/table-optimized/index.tsx
src/components/gui/table-result/render-cell.tsx

Since SQLite is flexible with types, we can't blindly trust the column-defined type. Instead, we now determine the display type based on the type of the received data.
**Here's how it works:**
- A `string` received type will be treated as `TEXT`.
- A `bigint` received type will be treated as `INTEGER` (since the `BigNumberCell` component handles `bigint`, which aligns with how `INTEGER` data is managed internally).
- A `number` received type will be treated as `REAL` (because the `NumberCell` component can handle `number`, which can represent both `integer` or `float` in JavaScript, so even if an `INTEGER` is treated as `number`, it won't be an issue).
- An `object` (Array) received type will be treated as `BLOB`.
- `BLOB` or `NULL` types are handled as generic types (managed by the …

fix: handle values according to their received type, not the column-defined type (fixes #137)

---

src/components/gui/sortable-tab.tsx
src/components/gui/tabs/table-data-tab.tsx
src/components/gui/windows-tab.tsx

This behavior is similar to Chrome or VSCode, where pressing the middle mouse button allows for easy tab closure.
**Additionally:**
- Improved the visual consistency between having no tabs and having tabs, ensuring the toolbar height remains the same.
- Enhanced the visual distinction between selected and unselected tabs, maintaining the visual position of elements to avoid unnecessary movement.

feat: added support for closing tabs with the middle mouse button

---

src/components/gui/table-cell/generic-cell.tsx

This is a pattern used by HeidiSQL: text is green to differentiate it from similar non-text, such as NULL.

refactor: use green color for texts (optional, suggestion)

---

src/app/globals.css
src/components/gui/table-cell/create-editable-cell.tsx
src/components/gui/table-cell/generic-cell.tsx
src/components/gui/table-result/render-cell.tsx
src/drivers/base-driver.ts
src/drivers/sqlite/sql-helper.ts

When a column is defined with one type (e.g., `INTEGER`) but stores a value of another type (e.g., `TEXT`), an indicator is displayed with a tooltip showing the mismatched type. This is very useful since SQLite has flexible typing, which can cause issues when the data is handled in an environment where this behavior is not expected.
**Important information:**
I had to modify a series of files to make this work properly, but I tried to do it in the best way possible. However, the `convertSqliteType()` function in the `sql-helper.ts` file made me the most "uncomfortable," since it's used in many places.
I had to make this change because there are cases where the type is not explicitly defined for SQLite, such as when accessing the default `sqlite_sequence` table. It defines `name` and …

feat: added a type mismatch indicator (fixes #138)

---

src/components/gui/table-cell/create-editable-cell.tsx

Currently, when a field enters edit mode, its height exceeds the outermost container's height. Applying the `flex` class forces it to respect the height limit, preventing the bottom border from disappearing.
**Before:**
**After:**

fix: prevent visual glitch when entering field edit mode

---

src/components/gui/table-cell/blob-cell.tsx
src/components/gui/table-cell/generic-cell.tsx
src/components/gui/table-optimized/OptimizeTableState.tsx
src/components/gui/table-result/render-cell.tsx
src/drivers/sqlite/sql-helper.ts

Characters that cannot be displayed legibly are transformed into `\x{XX}`.
I believe this change is valuable because sometimes I use BLOBs to store data that may or may not be encoded, depending on the context. And when they are not encoded, I would like to be able to read them. Additionally, it's better to be able to read as hex rather than base64.
**Before:**
**After:**
**Important:** the second commit provides the ability to **create and edit BLOB fields**, while the first commit only changes how they are displayed. The first commit is essential for making BLOBs more readable and easier to modify. However, you can accept the first commit without necessarily accepting the second.

refactor: try to display binary data (BLOB) whenever possible

---

src/components/gui/table-cell/display-link-cell.tsx
src/components/gui/table-cell/generic-cell.tsx

This feature had already been added to BLOBs; now it has been extended to other supported types as well, in case the content doesn’t fit within the box.
**Before:**
**After:**

feat: added ellipsis for large numbers, texts, and links

---

src/app/globals.css
src/components/gui/table-cell/generic-cell.tsx
src/components/gui/tabs/query-tab.tsx
src/drivers/sqljs-driver.ts

Since this driver does not report the column type, the type should be treated as `undefined`, which causes the type analysis system to be disabled for this driver.
---
Since you mentioned that you’re implementing MySQL support, it’s not necessary to approve this PR right now. When you're ready, let me know, and I’ll do a rebase and adjust whatever is needed.
As for this PR, in short, I just removed the internal indication that forced the `TEXT` type for all columns when using `sqljs` to be undefined. This way, the mismatch indicator system will be disabled.
I also migrated the code I had created in `global.css` to pure Tailwind, which I believe is ideal. I also fixed a typo.

fix: soft disable mismatch indicator for sqljs driver

---

src/app/(theme)/client/layout.tsx
src/app/(theme)/connect/page.tsx
src/app/(theme)/embed/sqlite/page-client.tsx
src/app/(theme)/embed/sqlite/page.tsx
src/app/(theme)/playground/client/page.tsx
src/app/(theme)/theme_layout.tsx
src/components/gui/connection-dialog.tsx
src/components/gui/sidebar-tab.tsx
src/components/gui/studio.tsx
src/components/my-studio.tsx
src/context/theme-provider.tsx

I have added two more options:
```
/embed/sqlite?theme=dark&disableThemeToggle=1
```
- `disableThemeToggle` will disable the change theme button
- `theme` will override which theme user want. `dark` | `light`
I also remove the go back button from the embed iframe.
I am not sure if it is what you want @KABBOUCHI

feat: add theme and disable theme toggle option

---

src/drivers/base-driver.ts
src/drivers/common-sql-imp.ts
src/drivers/mysql/mysql-driver.ts
src/drivers/postgres/postgres-driver.ts
src/drivers/query-builder.ts
src/drivers/sqlite-base-driver.ts

- Prevent fallback rowid for view
- Fix rowid fallback does not autofill because we switch using RETURNING. Now RETURNING will try to get rowid.

fixing fallback view and some minor bug related to rowid fallback

---

src/app/(outerbase)/w/[workspaceId]/[baseId]/page.tsx
src/drivers/mysql/mysql-driver.ts
src/outerbase-cloud/api-type.ts
src/outerbase-cloud/api-workspace.ts
src/outerbase-cloud/database/mysql.ts

We will not display other database tables when a user has specified a database in Outerbase Cloud. Since Outerbase Cloud does not run in interactive mode and does not support the USE statement, showing other databases would be unnecessary, as users cannot easily switch between them.

feat: show only the selected database for outerbase cloud

---

src/components/gui/query-explanation-diagram/index.tsx
src/components/gui/tabs/relational-diagram-tab/index.tsx

This pull request introduces improved theme support for the query explanation and relational diagram components.
It adds the theme obtained from the `useTheme` hook and applies the corresponding ReactFlow color mode. To maintain the same background color as before the change, the default dark mode background color is overridden.
|Before|After|
|---|---|
| <img width="1170" alt="SCR-20250308-qusj" src="https://github.com/user-attachments/assets/70a5a9b0-9867-4ed8-935a-82beee0e3ec2" /> | <img width="1171" alt="SCR-20250308-quwc" src="https://github.com/user-attachments/assets/1fe50bce-63f8-405f-9e58-cd87d3bf2061" /> |

fix: set correct color theme on diagrams

---

src/app/(outerbase)/local/hooks.tsx
src/app/api/events/insert-tracking-record.ts
src/components/editor/prompt-plugin.tsx
src/components/filehandler-picker.tsx
src/components/gui/schema-editor/index.tsx
src/components/gui/schema-editor/schema-editor-constraint-list.tsx
src/components/gui/table-result/context-menu.tsx
src/components/gui/tabs/schema-editor-tab.tsx
src/core/builtin-tab/open-query-tab.tsx
src/drivers/agent/common.ts
src/drivers/board-storage/local.ts
src/drivers/saved-doc/electron-saved-doc.ts
src/drivers/saved-doc/indexdb-saved-doc.ts
src/lib/generate-id.ts
src/lib/sql/sql-generate.schema.ts
src/lib/tracking.ts

Polyfill random uuid so that we can run it on http

refactor: polyfill for random uuid for insecure http

---

src/drivers/sqlite-base-driver.ts
src/drivers/sqlite/sql-parse-constraint.test.ts
src/drivers/sqlite/sql-parse-table.test.ts
src/drivers/sqlite/sql-parse-table.ts
src/drivers/sqlite/sql-parse-trigger.test.ts
src/drivers/sqlite/sql-parse-trigger.ts
src/drivers/sqlite/sql-parse-view.test.ts
src/drivers/sqlite/sql-parse-view.ts

Originally, we relied on CodeMirror's Lezer to build the AST and parsed from it. Now, we use our own tokenization approach. It produces a flat structure, and we build the parser on top of that. This gives us more flexibility for future extensions and reduces our dependency on external libraries.

Rewrite the sqlite create script parser.

---

src/components/gui/export/export-result-button.tsx
src/components/gui/schema-sidebar-list.tsx
src/components/gui/tabs/table-data-tab.tsx
src/lib/export-helper.ts

The pull request adds export functionality to the schema sidebar and includes a minor fix for non-negative validation on table data limits and offsets in the table data tab.

feat: Add export menu for tables. 
